### ISSUE TITLE
[Traefik Plugin Catalog] Plugin Analyzer has detected a problem.

### ISSUE THREAD

**Issue by traefiker** [Lightirius/traefik-auth-converter#1]
The plugin was not imported into Traefik Plugin Catalog.

Cause:
```
the import "github.com/lightirius/traefik-auth-converter" must be related to the module name "github.com/Lightirius/traefik-auth-converter"
```
Traefik Plugin Analyzer will restart when you will close this issue.

If you believe there is a problem with the Analyzer or this issue is the result of a false positive, please contact [us](https://community.traefik.io/).

**Comment by Lightirius** [comment]
Fixed in e731e2b
